# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blaze_version <- function(single) {
    .Call(`_RcppBlaze_blaze_version`, single)
}

testAs1 <- function(x) {
    .Call(`_RcppBlaze_testAs1`, x)
}

testWrap1 <- function() {
    .Call(`_RcppBlaze_testWrap1`)
}

